AppBundle\Entity\Card:
    type: entity
    table: card
    repositoryClass: AppBundle\Repository\CardRepository
    gedmo:
        translation:
            locale: locale
    manyToOne:
        set:
            targetEntity: Set
            inversedBy: cards
            joinColumn:
                name: set_id
                referencedColumnName: id
        type:
            targetEntity: Type
            inversedBy: cards
            joinColumn:
                name: type_id
                referencedColumnName: id
        faction:
            targetEntity: Faction
            inversedBy: cards
            joinColumn:
                name: faction_id
                referencedColumnName: id
        affiliation:
            targetEntity: Affiliation
            inversedBy: cards
            joinColumn:
                name: affiliation_id
                referencedColumnName: id
        rarity:
            targetEntity: Rarity
            inversedBy: cards
            joinColumn:
                name: rarity_id
                referencedColumnName: id
        reprintOf:
            targetEntity: Card
            inversedBy: reprints
            joinColumn:
                name: reprint_of
                referencedColumnName: id
        parallelDie:
            targetEntity: Card
            inversedBy: parallelDiceOf
            joinColumn:
                name: parallel_die
                referencedColumnName: id
    oneToMany:
        reprints:
            targetEntity: Card
            orderBy: {'code': 'ASC'}
            mappedBy: reprintOf
        parallelDiceOf:
            targetEntity: Card
            orderBy: {'code': 'ASC'}
            mappedBy: parallelDie
        reviews:
            targetEntity: Review
            orderBy: {'dateCreation':'DESC'}
            mappedBy: card
        sides:
            targetEntity: Side
            orderBy: {'id': 'ASC'}
            mappedBy: card
            fetch: EAGER
            cascade:
                - persist
                - remove
    manyToMany:
        subtypes:
            targetEntity: Subtype
            inversedBy: cards
            joinTable:
                name: card_subtype
                joinColumns:
                    card_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    subtype_id:
                        referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        position:
            type: smallint
            nullable: false
        code:
            type: string
            length: 255
            nullable: false
        ttscardid:
            type: string
            length: 255
            nullable: true
        name:
            type: string
            length: 50
            nullable: false
            gedmo:
                - translatable
        subtitle:
            type: string
            length: 50
            nullable: true
            gedmo:
                - translatable
        cost:
            type: smallint
            nullable: true
        health:
            type: smallint
            nullable: true
        points:
            type: string
            length: 20
            nullable: true
        text:
            type: text
            nullable: true
            gedmo:
                - translatable
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
        deckLimit:
            type: smallint
            nullable: true
            column: deck_limit
        flavor:
            type: text
            nullable: true
            gedmo:
                - translatable
        illustrator:
            type: string
            length: 255
            nullable: true
        isUnique:
            type: boolean
            nullable: false
            column: is_unique
        hasDie:
            type: boolean
            nullable: false
            column: has_die
        hasErrata:
            type: boolean
            nullable: false
            column: has_errata
        flipCard:
            type: boolean
            nullable: false
            column: flip_card
    uniqueConstraints:
        card_code_idx:
            columns: [ code ]
    indexes:
        card_name_idx:
            columns: [ name ]
